name: "NAIS Docker Build Push"
description: "Build and push docker image to the NAIS registry"
inputs:
  push_image:
    description: "Push image to registry"
    required: true
    default: "true"
  dockerfile:
    description: "Dockerfile"
    required: true
    default: "Dockerfile"
  docker_context:
    description: "Docker context"
    required: true
    default: "."
  tag:
    description: "Custom docker tag"
    required: false
  tag_latest:
    description: "Create latest docker tag"
    required: false
    default: "false"
  project_id:
    description: "Google Cloud project ID"
    required: true
  identity_provider:
    description: "Workload Identity Provider"
    required: true
  team:
    description: "Team slug"
    required: true
outputs:
  tag:
    description: "Release tag"
    value: ${{ steps.set-outputs.outputs.NEW_VERSION }}
  image:
    description: "Image name"
    value: ${{ steps.set-outputs.outputs.IMAGE }}
runs:
  using: "composite"
  steps:
    - name: NAIS login
      uses: nais/login@v0
      id: login
      with:
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        team: ${{ inputs.team }}
    - name: Setup environment
      shell: bash
      id: "setup"
      run: |
        echo "REPO_NAME=${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}" >> $GITHUB_OUTPUT
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ steps.login.outputs.registry }}/${{ steps.setup.outputs.REPO_NAME }}
        tags: |
          type=raw,enable=${{ inputs.tag != '' }},value=${{ inputs.tag }},priority=9002
          type=sha,prefix={{date 'YYYY-MM-DD'}}-,priority=9001
          type=raw,enable=${{ inputs.tag_latest == 'true' }},value=latest,priority=9000
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push_image }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    # For some reason, nested composite outputs aren't properly evaluated, so we need to set them again. 
    - name: Set outputs
      shell: bash
      id: set-outputs
      run: |
        echo "NEW_VERSION=${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
        echo "IMAGE=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT

